{{- if .Values.enabled -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          env:
            - name: CONFIG_TEMPLATE_DIRECTORY
              value: '/etc/gitaly/templates'
            - name: CONFIG_DIRECTORY
              value: '/etc/gitaly'
          volumeMounts:
            - name: gitaly-config
              mountPath: '/etc/gitaly/templates'
            - name: gitaly-secret
              mountPath: '/etc/gitlab-secrets'
              readOnly: true
            - name: gitaly-shell
              mountPath: '/etc/gitlab-secrets'
              readOnly: true
            - name: gitaly-redis
              mountPath: '/etc/gitlab-secrets'
              readOnly: true
          livenessProbe:
            exec:
              command:
              - /scripts/healthcheck
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
              - /scripts/healthcheck
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 10
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
      - name: gitaly-config
        configMap:
          name: {{ template "fullname" . }}
      - name: gitaly-secret
        secret:
          secretName: {{ .Values.secret.name }}
          items:
            - key: {{ .Values.secret.key }}
              path: "gitaly_token"
          defaultMode: 0440
      - name: gitaly-shell
        secret:
          secretName: {{ .Values.shell.secret }}
          items:
            - key: {{ .Values.shell.key }}
              path: ".gitlab_shell_secret"
          defaultMode: 0440
      - name: gitaly-redis
        secret:
          secretName: {{ .Values.redis.password.secret }}
          items:
            - key: {{ .Values.redis.password.key }}
              path: redis_password
          defaultMode: 0440
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
{{- end }}
