apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
{{ include "gitlab.standardLabels" . | indent 4 }}
data:
  generate-secrets: |
{{ include (print $.Template.BasePath "/_generate_secrets.sh") . | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-shared-secrets-jobspec
  labels:
{{ include "gitlab.standardLabels" . | indent 4 }}
data:
  template: |-
{{ include (print $.Template.BasePath "/_jobspec.yaml") . | indent 4 }}
  role: |-
{{ include (print $.Template.BasePath "/_rbac-role.yaml") . | indent 4}}
  serviceAccount: |-
{{ include (print $.Template.BasePath "/_rbac-serviceaccount.yaml") . | indent 4 }}
  roleBinding: |-
{{ include (print $.Template.BasePath "/_rbac-rolebinding.yaml") . | indent 4 }}
